#import "./movefragment.gql"
mutation insertMove($input: [move_insert_input!]!, $userId: String) {
  insert_move(
    objects: $input,
    on_conflict: {
      constraint: move_pkey,
      update_columns: [name, characterName, noteText, onBlock, onCounterhit, onHit, startupFrames, buttonInput]
    }) {
    returning {
      ...move
      liked(args: {user_id: $userId})
    }
  }
}