mutation insertMove($input: [move_insert_input!]!) {
  insert_move(
    objects: $input,
    on_conflict: {
      constraint: move_pkey,
      update_columns: [name, noteText, onBlock, onCounterhit, onHit, startupFrames, buttonInput]
    }) {
    returning {
      id
      name
      noteText
      onBlock
      onCounterhit
      onHit
      startupFrames
      buttonInput
      createdAt
    }
  }
}