query latestMoves($userId: String) {
  move(order_by: {createdAt: desc}, limit: 10) {
    name
    characterName
    character {
      portrait
    }
    noteText
    onCounterhit
    onBlock
    onHit
    startupFrames
    buttonInput
    createdAt
    id
    likes_aggregate {
      aggregate {
        count
      }
    }
    liked(args: {user_id: $userId})
  }
}