query userWithMoves {
  user {
    moves {
      name
      characterName
      noteText
      onCounterhit
      onBlock
      onHit
      startupFrames
      buttonInput
      createdAt
      id
    }
    id
  }
}