query userWithMoves($userId: String) {
  user {
    moves {
      name
      characterName
      character {
        portrait
      }
      noteText
      onCounterhit
      onBlock
      onHit
      startupFrames
      buttonInput
      createdAt
      id
      likes_aggregate {
        aggregate {
          count
        }
      }
      liked(args: {user_id: $userId})
    }
    id
  }
}